In [1]:
import torch
import torch.nn as nn

from tqdm.notebook import tqdm

from typing import List

import numpy as np

## Gradient Descent

In [2]:
def reconstruct(
    P: torch.FloatTensor,
    Q: torch.FloatTensor,
    bu: torch.FloatTensor,
    bi: torch.FloatTensor,
    mu: float,
) -> torch.FloatTensor:
    P = P.cuda()
    Q = Q.cuda()
    bu = bu.cuda()
    bi = bi.cuda()
    
    Bu = torch.concat((bu, torch.ones(len(bu), 1, device="cuda")), dim=1)
    Bi = torch.concat((bi, torch.ones(len(bi), 1, device="cuda")), dim=1)
    
    mat = mu + Bu@Bi.T + P@Q.T
    
    return torch.clip(mat, 1, 5).cpu()

In [3]:
def fit(
    uir_mat: torch.IntTensor, # User Item rating mat
    k: int,
    lr: float,
    λ: float,
    iters: int,
    n_users: int,
    n_movies: int,
    mu: float = None,
    uir_val: torch.IntTensor = None
) -> List[torch.FloatTensor]:
    train_losses = np.zeros(iters)
    val_losses = np.zeros(iters)
    
    # Initialize params
    uir_mat = uir_mat.cuda()
    expected = uir_mat[:, 2].float()
    n_interactions = expected.shape[0]
    
    if uir_val is not None:
        uir_val = uir_val.cuda()
        expected_val = uir_val[:, 2].float()
        n_interactions_val = expected_val.shape[0]
    
    P = torch.rand(n_users, k, requires_grad=True, device="cuda")
    Q = torch.rand(n_movies, k, requires_grad=True, device="cuda")
    with torch.no_grad():
        P *= .1
        Q *= .1
    bu = torch.rand(n_users, 1, requires_grad=True, device="cuda")
    bi = torch.rand(n_movies, 1, requires_grad=True, device="cuda")
    
    if mu is None:
        mu = (expected.sum()/(expected!=0).sum())

#     criterion = nn.MSELoss()
    
    # Fit
    ones_user = torch.ones(n_users, 1, requires_grad=False, device="cuda")
    ones_item = torch.ones(n_movies, 1, requires_grad=False, device="cuda")

    min_loss = torch.inf
    params = []
    
    val_loss = torch.inf
    for i in tqdm(range(iters)):
        Bu = torch.concat((bu, ones_user), dim=1)
        Bi = torch.concat((ones_item, bi), dim=1)

        pred_mat = mu + Bu@(Bi.T) + P@(Q.T)

        # Calculate gradient only respect to know ratings
        pred = pred_mat[uir_mat[:, 0], uir_mat[:, 1]]

#         loss = criterion(pred, expected)
        # Regularized rmse
#         loss = 1/(2*n_interactions) * torch.sum((pred - expected)**2)
        loss = 1/(2*n_interactions) * torch.sum((pred - expected)**2) + λ*(torch.sum(P**2) + torch.sum(Q**2))
        train_losses[i] = float(loss.detach())
        
        if min_loss > loss.detach():
            min_loss = float(loss.detach())
            params = [P.detach().cpu(), Q.detach().cpu(), bu.detach().cpu(), bi.detach().cpu()]
#             print(f"iter {i+1}: {min_loss}")

        loss.backward()

        with torch.no_grad():
            # Validation error
            if uir_val is not None:
                pred_val = pred_mat[uir_val[:, 0], uir_val[:, 1]]
                const = 1/(2*n_interactions_val)
                val_loss = const * torch.sum((pred_val - expected_val)**2) + λ/2*(torch.sum(P**2) + torch.sum(Q**2))
                val_losses[i] = float(val_loss)
            
            P -= lr*P.grad
            Q -= lr*Q.grad
            bu -= lr*bu.grad
            bi -= lr*bi.grad
            
        P.grad.zero_()
        Q.grad.zero_()
        bu.grad.zero_()
        bi.grad.zero_()
            
    print("train:", min_loss)
    print("val:", float(val_loss))
    return params, train_losses, val_losses

In [4]:
## Test
mat = torch.tensor([
    [5, 2, 4, 3, 2, 3],
    [4, 3, 5, 4, 3, 2],
    [1, 5, 3, 4, 4, 5],
    [1, 0, 2, 3, 4, 2],
], dtype=torch.float32)
uir_test_mat = torch.zeros(mat.shape[0]*mat.shape[1] -1, 3, dtype=torch.long)
k = 0
for i in range(mat.shape[0]):
    for j in range(mat.shape[1]):
        if mat[i, j] != 0:
            uir_test_mat[k] = torch.tensor([i, j, mat[i, j]])
            k += 1

(out_P, out_Q, out_bu, out_bi), _, _ = fit(
    uir_mat=uir_test_mat, 
    k=3, 
    lr=0.08, 
    λ=0.01, 
    iters=70, 
    n_users=4, 
    n_movies=6
)

  0%|          | 0/70 [00:00<?, ?it/s]

train: 0.6085423827171326
val: inf


In [5]:
out_mat = reconstruct(out_P, out_Q, out_bu, out_bi, (mat.sum()/(mat!=0).sum()))

print(out_mat)
print()
print(mat)

tensor([[4.2375, 4.2106, 4.2071, 4.1784, 4.2153, 4.2005],
        [4.1981, 4.2254, 4.2488, 4.2760, 4.2297, 4.2357],
        [4.1518, 4.2458, 4.2871, 4.3826, 4.2468, 4.2799],
        [4.3330, 4.1835, 4.1013, 3.9349, 4.1955, 4.1185]])

tensor([[5., 2., 4., 3., 2., 3.],
        [4., 3., 5., 4., 3., 2.],
        [1., 5., 3., 4., 4., 5.],
        [1., 0., 2., 3., 4., 2.]])


# Real Data

In [6]:
import numpy as np
from numpy.typing import NDArray
import pandas as pd
from numba import njit, prange

In [8]:
users = 3974
movies = 3564

train_csv = pd.read_csv("../../../data/train_data.csv")
test_csv = pd.read_csv("../../../data/test_data.csv")

train_csv["user_id"] = train_csv["user_id"].apply(lambda x: x - 1)
train_csv["movie_id"] = train_csv["movie_id"].apply(lambda x: x - 1)

test_csv["user_id"] = test_csv["user_id"].apply(lambda x: x - 1)
test_csv["movie_id"] = test_csv["movie_id"].apply(lambda x: x - 1)

# Split into train and validation
train_data = train_csv.drop(["timestamp"], axis=1).sample(frac=0.8)
validation_data = train_csv.drop(train_data.index).drop(["timestamp"], axis=1)

assert train_data.shape[0] + validation_data.shape[0] == train_csv.shape[0]## Split into train and validation

# Fit

In [9]:
import matplotlib.pyplot as plt

In [10]:
uir_train = train_data.values
mu_train = np.mean(uir_train[:, 2])
uir_train_tensor = torch.from_numpy(uir_train)

uir_val = validation_data.values
n_val = uir_val.shape[0]
uir_val_tensor = torch.from_numpy(uir_val)

In [11]:
min_err = np.inf
best_k = 2
# for k in tqdm(range(2, 4)):
for k in tqdm(range(98, 101)):
    fitted_params, tr_loss, v_loss = fit(
        uir_mat=uir_train_tensor,
        k=50,
        lr=0.8, 
        λ=0.01, 
        iters=1000, 
        n_users=users, 
        n_movies=movies, 
        mu=mu_train,
        uir_val=uir_val_tensor,
    )
    recontructed_mat = reconstruct(*fitted_params, mu_train).numpy()
    
    predicted = recontructed_mat[uir_val[:, 0], uir_val[:, 1]]
    
#     predicted = predicted.round()
    err = 1/(2*n_val) * np.sum((predicted - uir_val[:, 2])**2)
    
#     plt.plot(tr_loss[-300:])
#     plt.plot(v_loss[-300:])
#     plt.show()
    
    if min_err > err:
        min_err = err
        best_k = k

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1000 [00:00<?, ?it/s]

train: 0.6689586639404297
val: 0.6700192093849182


  0%|          | 0/1000 [00:00<?, ?it/s]

train: 0.6626609563827515
val: 0.6648584008216858


  0%|          | 0/1000 [00:00<?, ?it/s]

train: 0.6655436754226685
val: 0.6686933040618896


In [12]:
predicted[:50]

array([4.6212215, 4.65078  , 4.646514 , 4.6297665, 4.716919 , 4.5182514,
       4.5998006, 4.4203005, 4.709689 , 4.8711176, 4.6422086, 4.661655 ,
       4.6558094, 4.5999665, 5.       , 4.7250853, 4.730851 , 4.671728 ,
       4.649667 , 4.802049 , 5.       , 4.8535256, 5.       , 4.6428146,
       4.6813803, 4.704528 , 4.7896814, 4.647318 , 4.60566  , 4.6171503,
       4.641992 , 4.9300146, 5.       , 4.908063 , 4.701    , 4.7205634,
       4.936112 , 4.7821484, 4.861743 , 4.6968956, 4.5826526, 4.738677 ,
       4.8444386, 4.5223904, 4.9432487, 4.6296134, 4.486174 , 4.763527 ,
       4.59197  , 4.883722 ], dtype=float32)

In [21]:
print(best_k, min_err)

99 1.1370220181616322


## Predict

In [19]:
uir_full = train_csv.drop(["timestamp"], axis=1).values
uir_full = torch.from_numpy(uir_full)
mu_full = torch.mean(uir_full[:, 2].float())

fitted_params = fit(
    uir_mat=uir_full, k=best_k, lr=0.8, λ=0.01, iters=1, n_users=users, n_movies=movies, mu=mu_full)

  0%|          | 0/1 [00:00<?, ?it/s]

train: 26.34429931640625
val: inf


In [20]:
len(fitted_params)

3

In [16]:
recontructed_mat = reconstruct(*fitted_params, mu=mu_full).numpy()

TypeError: reconstruct() missing 2 required positional arguments: 'bi' and 'mu'

In [ ]:
# test_predictions = predict_batch(
#     test_csv.drop(["id", "timestamp"], axis=1).values,
#     recontructed_mat,
# )
uir_test = test_csv.drop(["id", "timestamp"], axis=1).values
test_predictions = recontructed_mat[uir_test[:, 0], uir_test[:, 1]]
print(test_predictions[:10])

In [ ]:
out_df = pd.DataFrame.from_dict(
    {
        "id": list(test_csv["id"]),
        "rating": test_predictions
    }
)

out_df.head()

In [ ]:
out_df.to_csv("out_funk_svd_1.csv", index=False)