In [1]:
import numpy as np
import pandas as pd
from numba import njit, prange
from numpy.typing import NDArray

In [2]:
np.set_printoptions(suppress=True)

In [3]:
train_csv = pd.read_csv("../../data/train_data.csv")
test_csv = pd.read_csv("../../data/test_data.csv")

# Split into train and validation
train_data = train_csv.drop(["timestamp"], axis=1).sample(frac=0.8)
validation_data = train_csv.drop(train_data.index).drop(["timestamp"], axis=1)

assert train_data.shape[0] + validation_data.shape[0] == train_csv.shape[0]## Split into train and validation

(nxm) = (nxk) x (kxk) x (kxm)

(4x6) = (4x4) x (4x4) x (4x6)

In [4]:
test_mat = np.array([
    [5, 2, 4, 3, 2, 3],
    [4, 3, 5, 4, 3, 2],
    [1, 5, 3, 4, 4, 5],
    [1, 0, 2, 3, 4, 2],
])

In [13]:
U, S, V = np.linalg.svd(test_mat)

print(U.shape)
print(U)

(4, 4)
[[-0.49886556 -0.54387192  0.15566362 -0.65658611]
 [-0.55809113 -0.37497062  0.02218797  0.73989122]
 [-0.57732384  0.72729484  0.36289412 -0.07776413]
 [-0.32613591  0.18612518 -0.9184685  -0.12413059]]


In [14]:
print(S.shape)
print(S)

(4,)
[15.51117567  4.47565753  3.01731438  1.5058994 ]


In [23]:
print(V.shape)
print(V.T[:, :len(S)])

(6, 6)
[[-0.36297391 -0.73862266  0.10323606 -0.34880181]
 [-0.3583625   0.31812498  0.72659376  0.34376848]
 [-0.46225775 -0.33429857 -0.00485871  0.39282707]
 [-0.45236186  0.07508542 -0.24793116  0.20343871]
 [-0.4052461   0.32196931 -0.61127417  0.06569   ]
 [-0.39659598  0.36355944  0.16203165 -0.74842832]]


In [22]:
U@np.diag(S)@V[:4]

array([[5., 2., 4., 3., 2., 3.],
       [4., 3., 5., 4., 3., 2.],
       [1., 5., 3., 4., 4., 5.],
       [1., 0., 2., 3., 4., 2.]])

$U$ is the users matrix (n_users x n_features)\
$V^T$ is the items matrix (n_items x n_features)

## Reducing the dimension

In [27]:
# Taking 2 latent factors
k = 2
Uk = U[:, :k]
Sk = S[:k]
Vtk = V.T[:, :k]

print(Uk.shape, Sk.shape, Vtk.shape)

(4, 2) (2,) (6, 2)


In [30]:
reconstructed = Uk@np.diag(Sk)@Vtk.T
print(reconstructed)

[[4.60663275 1.99863101 4.39069087 3.31760037 2.35205814 2.18388551]
 [4.38172412 2.5683285  4.56263668 3.78992676 2.96773172 2.82305242]
 [0.84611364 4.24466179 3.05132212 4.29529978 4.67701685 4.73493624]
 [1.22089804 2.07787526 2.05996545 2.35093478 2.31825019 2.30913731]]
