In [3]:
import torch
import numpy as np

In [11]:
a, b, c, d = 3., 6., 9., 12.

In [13]:
theta = torch.tensor([
    [a],
    [b],
    [c]
], requires_grad=True)
ones_row = torch.ones(3, 1, requires_grad=False)

A = torch.concat((theta, ones_row), dim=1)
print(A)

tensor([[3., 1.],
        [6., 1.],
        [9., 1.]], grad_fn=<CatBackward0>)


In [15]:
B = torch.tensor([
    [1],
    [d],
], requires_grad=False)

print(B)

tensor([[ 1.],
        [12.]])


In [20]:
out = A@B
print(out)

tensor([[15.],
        [18.],
        [21.]], grad_fn=<MmBackward0>)


In [22]:
print(theta.grad)

None


In [25]:
out[0].backward()

In [26]:
theta.grad

tensor([[1.],
        [0.],
        [0.]])